# Generated by Django 2.0.9 on 2018-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SvnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_n', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=40, null=True)),
                ('base_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'svn_list',
                'managed': True,
            },
        ),
    ]
